version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: sailer-db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./app/sql:/docker-entrypoint-initdb.d

  api:
    build: .
    container_name: sailer-api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
