version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: sailer-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sailer
      MYSQL_USER: sailer
      MYSQL_PASSWORD: sailer
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
